# Generated by Django 4.0 on 2022-02-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='post_uchun')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(blank=True, max_length=300)),
                ('joy', models.CharField(blank=True, max_length=300)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('accaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_posts', to='userapp.account')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.media')),
                ('tag', models.ManyToManyField(blank=True, related_name='account_tags', to='userapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(blank=True, max_length=150)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='feed.media')),
                ('qabul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_qabul', to='userapp.account')),
                ('yuboruvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_yuboruvchi', to='userapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=150)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('accaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.account')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.comments')),
            ],
        ),
    ]
